<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>set-api</artifactId>
		<groupId>eu.europeana.set</groupId>
		<relativePath>../pom.xml</relativePath>
		<version>0.15-SNAPSHOT</version>
	</parent>

	<artifactId>set-definitions</artifactId>
	<name>Europeana (User) Set - Definitions</name>
	<organization>
		<name>Europeana Foundation + AIT</name>
	</organization>
	<url>http://www.europeanalabs.eu</url>
	
	<dependencies>
		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>commons-sb3-definitions</artifactId>
			<version>${version.commons.api.sb3}</version>
		</dependency>
	</dependencies>
</project>
