<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>set-api</artifactId>
        <groupId>eu.europeana.set</groupId>
        <relativePath>../pom.xml</relativePath>
        <version>0.14-SNAPSHOT</version>
    </parent>

    <artifactId>set-usage-stats</artifactId>
    <name>Europeana (User) Set - Usage Stats</name>
    <organization>
        <name>Europeana Foundation + AIT</name>
    </organization>
    <url>http://www.europeanalabs.eu</url>
    
    <dependencies>
        <!-- set projects -->
        <dependency>
            <groupId>eu.europeana.set</groupId>
            <artifactId>set-mongo</artifactId>
            <version>0.14-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>${version.jakarta-ws.rs}</version>
        </dependency>


    </dependencies>
</project>