<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>set-web</artifactId>
	<name>Europeana (User) Sets - WEB API </name>
	<packaging>jar</packaging>
	<description>The implementation of the User Sets REST service</description>

	<parent>
		<artifactId>set-api</artifactId>
		<groupId>eu.europeana.set</groupId>
		<relativePath>../pom.xml</relativePath>
		<version>0.14</version>
	</parent>

	<dependencies>
		<!-- set projects -->
		<dependency>
			<groupId>eu.europeana.set</groupId>
			<artifactId>set-common</artifactId>
			<version>0.14</version>
		</dependency>
		<dependency>
			<groupId>eu.europeana.set</groupId>
			<artifactId>set-mongo</artifactId>
			<version>0.14</version>
		</dependency>

		<dependency>
			<groupId>eu.europeana.set</groupId>
			<artifactId>set-search-api-client</artifactId>
			<version>0.14</version>
		</dependency>

		<dependency>
			<groupId>eu.europeana.set</groupId>
			<artifactId>set-usage-stats</artifactId>
			<version>0.14</version>
		</dependency>

		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>commons-sb3-oauth</artifactId>
			<version>${version.commons.api.sb3}</version>
		</dependency>

		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>commons-sb3-nosql</artifactId>
			<version>${version.commons.api.sb3}</version>
		</dependency>

		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>commons-sb3-search</artifactId>
			<version>${version.commons.api.sb3}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.solr</groupId>
					<artifactId>solr-solrj</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- spring dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<!-- use log4j2 instead -->
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<!-- aspectj /profiling -->
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>${swagger.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>slf4j-api</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${swagger.version}</version>
		</dependency>

		<!-- swagger -->
		<!-- spring doc dependencies -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>${springdoc.version}</version>
		</dependency>

		<!--  jakarta.servlet -->
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${version.commonsIO}</version>
			<scope>compile</scope>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/ jakarta.validation/validation-api -->
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**.properties</include>
					<include>**.info</include>
					<include>**.xml</include>
				</includes>
				<excludes>
					<exclude>**/*.jks</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/*.jks</include>
					<include>public/**</include>
				</includes>
			</resource>
		</resources>
		<finalName>${project.artifactId}</finalName>
		<!-- plugins -->
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<classifier>executable</classifier>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>
