apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  #selector:
  #  matchLabels:
  #    app: set-api
  template:
    spec:
      containers:
      - name: set-api
        image: europeana/set-api
        env:
          - name: SPRING_CONFIG_NAME
            value: "set.common,set.user"
          - name: SPRING_CONFIG_ADDITIONAL_LOCATION
            value: "/opt/app/config/set.user.properties"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
          - name: app-properties
            mountPath: "/opt/app/config/set.user.properties"
            readOnly: true
            subPath: set.user.properties
      volumes:
        - name: app-properties
          secret:
            secretName: set-api-properties
