apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  selector:
    matchLabels:
      app: set-api
  template:
    spec:
      containers:
      - name: set-api
        image: europeana/set-api
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/info
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/info
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
          - name: secret
            mountPath: "/config/set.user.properties"
            readOnly: true
            subPath: set.user.properties
      volumes:
      - name: secret
        secret:
          secretName: set-api-secret