apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  selector:
    matchLabels:
      app: set-api
  template:
    spec:
      containers:
      - name: set-api
        image: europeana/set-api
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
          - name: SPRING_CONFIG_ADDITIONAL_LOCATION
            value: "file:/opt/app/"
        volumeMounts:
          - name: app-properties
            mountPath: "/opt/app/config/set.user.properties"
            readOnly: true
            subPath: set.user.properties
      volumes:
      - name: app-properties
        secret:
          secretName: set-api-properties