resources:
  - deployment.yaml

commonLabels:
  app: set-api

# expects files to be in the same directory
secretGenerator:
  - name: set-api-properties
    files:
      - set.user.properties
  - name: ibm-secret
    files:
      - ibm-databases-truststore.jks