resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: set-api

# expects files to be in the same directory
secretGenerator:
  - name: set-api-properties
    files:
      - set.user.properties