apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-api-deployment
spec:
  template:
    spec:
      containers:
      - name: set-api
        # required to use local image
        imagePullPolicy: Never